
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">
    <title>PPDB - YAPPIKA</title>
    <!-- Simple bar CSS -->
    <link rel="stylesheet" href="<?= $this->baseUrl('css/simplebar.css'); ?>'); ?>">
    <!-- Fonts CSS -->
    <link href="https://fonts.googleapis.com/css2?family=Overpass:ital,wght@0,100;0,200;0,300;0,400;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <!-- Icons CSS -->
    <link rel="stylesheet" href="<?= $this->baseUrl('css/feather.css'); ?>">
    <!-- Date Range Picker CSS -->
    <link rel="stylesheet" href="<?= $this->baseUrl('css/daterangepicker.css'); ?>">
    <!-- App CSS -->
    <link rel="stylesheet" href="<?= $this->baseUrl('css/app-light.css'); ?>" id="lightTheme">
    <link rel="stylesheet" href="<?= $this->baseUrl('css/app-dark.css'); ?>" id="darkTheme" disabled>
  </head>
  <body class="light ">
    <div class="wrapper vh-100">
      <div class="row align-items-center h-100">
        <form class="col-lg-3 col-md-4 col-10 mx-auto text-center" action="" method="POST">
          <div class="mx-auto text-center my-4">
            <a class="navbar-brand mx-auto mt-2 flex-fill text-center" href="">
              <img src="<?= $this->baseUrl('media/logosekolah.jpeg')?>" alt="SMK YAPPIKA" width="175" heigh="175" class="navbar-brand mx-auto mt-2 flex-fill text-center">
            <h1 class="my-3">SMK YAPPIKA LEGOK</h1>
            </a>
            <br><br>
            <h2 class="my-3">Reset Password</h2>
            <?=$this->notif;?>
          </div>
          <!-- <p class="text-muted">Enter your email address and we'll send you an email with instructions to reset your password</p> -->
          <div class="form-group">
            <label for="inputPasswordx" class="sr-only">Password Lama</label>
            <input name="passw_lama" type="password" id="inputPasswordx" class="form-control form-control-lg" placeholder="Password Lama" required>
            <br>
            <label for="inputPassword" class="sr-only">Password Baru</label>
            <input name="passw_baru" type="password" id="inputPassword" class="form-control form-control-lg" placeholder="Password Baru" required>
          </div>
          <button class="btn btn-lg btn-primary btn-block" type="submit" name="submit" value="update">Reset Password</button>
          <p class="mt-5 mb-3 text-muted">© 2022</p>
        </form>
      </div>
    </div>
    <script src="<?= $this->baseUrl('js/jquery.min.js')?>"></script>
    <script src="<?= $this->baseUrl('js/popper.min.js')?>"></script>
    <script src="<?= $this->baseUrl('js/moment.min.js')?>"></script>
    <script src="<?= $this->baseUrl('js/bootstrap.min.js')?>"></script>
    <script src="<?= $this->baseUrl('js/simplebar.min.js')?>"></script>
    <script src='<?= $this->baseUrl('js/daterangepicker.js')?>'></script>
    <script src='<?= $this->baseUrl('js/jquery.stickOnScroll.js')?>'></script>
    <script src="<?= $this->baseUrl('js/tinycolor-min.js')?>"></script>
    <script src="<?= $this->baseUrl('js/config.js')?>"></script>
    <script src="<?= $this->baseUrl('js/apps.js')?>"></script>
  </body>
</html>
</body>
</html>