<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">
    <title>PPDB - YAPPIKA</title>
    <!-- Simple bar CSS -->
    <link rel="stylesheet" href="css/simplebar.css">
    <!-- Fonts CSS -->
    <link href="https://fonts.googleapis.com/css2?family=Overpass:ital,wght@0,100;0,200;0,300;0,400;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <!-- Icons CSS -->
    <link rel="stylesheet" href="<?= $this->baseUrl('css/feather.css')?>">
    <link rel="stylesheet" href="<?= $this->baseUrl('css/select2.css')?>">
    <link rel="stylesheet" href="<?= $this->baseUrl('css/dropzone.css')?>">
    <link rel="stylesheet" href="<?= $this->baseUrl('css/uppy.min.css')?>">
    <link rel="stylesheet" href="<?= $this->baseUrl('css/jquery.steps.css')?>">
    <link rel="stylesheet" href="<?= $this->baseUrl('css/jquery.timepicker.css')?>">
    <link rel="stylesheet" href="<?= $this->baseUrl('css/quill.snow.css')?>">
    <!-- Date Range Picker CSS -->
    <link rel="stylesheet" href="<?= $this->baseUrl('css/daterangepicker.css')?>">
    <!-- App CSS -->
    <link rel="stylesheet" href="<?= $this->baseUrl('css/app-light.css')?>" id="lightTheme">
    <link rel="stylesheet" href="<?= $this->baseUrl('css/app-dark.css')?>" id="darkTheme" disabled>
  </head>
  <body class="vertical  light  ">
    <div class="wrapper">

      <nav class="topnav navbar navbar-light">
        <ul class="nav">
          <li class="nav-item">
            <a class="nav-link text-muted my-2" href="#" id="modeSwitcher" data-mode="light" title="DARK / LIGHT Mode">
              <i class="fe fe-sun fe-16"></i>
            </a>
          </li>
        </ul>
      </nav>

      <aside class="sidebar-left border-right bg-white shadow" id="leftSidebar" data-simplebar>
        <a href="#" class="btn collapseSidebar toggle-btn d-lg-none text-muted ml-2 mt-3" data-toggle="toggle">
          <i class="fe fe-x"><span class="sr-only"></span></i>
        </a>
        <nav class="vertnav navbar navbar-light">
         <div class="w-100 mb-4 d-flex">
            <img src="<?= $this->baseUrl('media/logosekolah.jpeg')?>" alt="SMK YAPPIKA" width="25" heigh="25" class="navbar-brand md-auto mt-2 flex-fill text-center">
          </div>
          <p class="navbar-brand mx-auto mt-2 flex-fill text-center">SMK YAPPIKA LEGOK</p>

          <ul class="navbar-nav flex-fill w-100 mb-2">
            <li class="nav-item w-100">
              <a class="nav-link" href="#">
                <i class="fe fe-file fe-16"></i>
                <span class="ml-3 item-text">Soal</span>
              </a>
            </li>
          </ul>
        </nav>
      </aside> 
      <main role="main" class="main-content">
        <div class="container-fluid">
          <div class="row justify-content-center">
            <div class="col-12 col-lg-12">
              <h2 class="page-title">SOAL KEJURUAN MULTIMEDIA</h2>
              <p>Isilah jawaban sesuai dengan yang anda ketahui.</p>
              <div class="card my-4">
                <div class="card-header">
                  <strong></strong>
                </div>
                  <div class="card-body">
                    
                    <div id='dvLoading' style='display:none;'></div>
                    
                    <form class="" id="soal" action="#" method="post">
                    <form class="" id="soal" action="#" method="post">
                      <div id="example-vertical">
                        <?php
                          foreach($this->list_soal as $val) {
                        ?>
                          <h3 id="kd_soal"><?= $val['soal']?></h3>
                          
                          <section>
                            <div class="form-group">
                                <label for="userName">Jawab*</label>
                                <div class="custom-control custom-radio mb-2 <?= $val['kejuruan']?>">
                                  <input type="radio" class="custom-control-input" id="<?= $val['jawaban_a']?>" name="<?= $val['kd_soal']?>" value="a">
                                  <label class="custom-control-label" for="<?= $val['jawaban_a']?>"><b>A.</b>  <?= $val['jawaban_a']?></label>
                                </div>
                                <div class="custom-control custom-radio mb-2 <?= $val['kejuruan']?>">
                                  <input type="radio" class="custom-control-input" id="<?= $val['jawaban_b']?>" name="<?= $val['kd_soal']?>" value="b">
                                  <label class="custom-control-label" for="<?= $val['jawaban_b']?>"><b>B.</b>  <?= $val['jawaban_b']?></label>
                              </div>
                                <div class="custom-control custom-radio mb-2 <?= $val['kejuruan']?>">
                                  <input type="radio" class="custom-control-input" id="<?= $val['jawaban_c']?>" name="<?= $val['kd_soal']?>" value="c">
                                  <label class="custom-control-label" for="<?= $val['jawaban_c']?>"><b>C.</b>  <?= $val['jawaban_c']?></label>
                                </div>
                                <div class="custom-control custom-radio mb-2 <?= $val['kejuruan']?>">
                                  <input type="radio" class="custom-control-input" id="<?= $val['jawaban_d']?>" name="<?= $val['kd_soal']?>" value="d">
                                  <label class="custom-control-label" for="<?= $val['jawaban_d']?>"><b>D.</b>  <?= $val['jawaban_d']?></label>
                                </div>
                                <div class="custom-control custom-radio mb-3 <?= $val['kejuruan']?>">
                                  <input type="radio" class="custom-control-input" id="<?= $val['jawaban_e']?>" name="<?= $val['kd_soal']?>" value="e">
                                  <label class="custom-control-label" for="<?= $val['jawaban_e']?>"><b>E.</b>  <?= $val['jawaban_e']?></label>
                                </div>
                                <div class='mm1'>
                                  <input type='hidden' id='textjwb' name='asd' value='' disabled/>
                                  <input type='hidden' id='kejuruan' name='kejuruan' value='<?= $val['kejuruan']?>' disabled/>
                                </div>
                              </div>
                          </section>
                        <?php

                            
                          }
                        ?>
                      </div>
                    </form>
                  </div> <!-- .card-body -->                
              </div> <!-- .card -->
            </div> <!-- .col-12 -->
          </div> <!-- .row -->
        </div> <!-- .container-fluid -->
      </main> <!-- main -->
    </div> <!-- .wrapper -->
    <script src="<?= $this->baseUrl('js/jquery.min.js');?>"></script>
    <script src="<?= $this->baseUrl('js/popper.min.js');?>"></script>
    <script src="<?= $this->baseUrl('js/moment.min.js');?>"></script>
    <script src="<?= $this->baseUrl('js/bootstrap.min.js');?>"></script>
    <script src="<?= $this->baseUrl('js/simplebar.min.js');?>"></script>
    <script src='<?= $this->baseUrl('js/daterangepicker.js');?>'></script>
    <script src='<?= $this->baseUrl('js/jquery.stickOnScroll.js');?>'></script>
    <script src="<?= $this->baseUrl('js/tinycolor-min.js');?>"></script>
    <script src="<?= $this->baseUrl('js/config.js');?>"></script>
    <script src="<?= $this->baseUrl('js/d3.min.js');?>"></script>
    <script src="<?= $this->baseUrl('js/topojson.min.js');?>"></script>
    <script src="<?= $this->baseUrl('js/datamaps.all.min.js');?>"></script>
    <script src="<?= $this->baseUrl('js/datamaps-zoomto.js');?>"></script>
    <script src="<?= $this->baseUrl('js/datamaps.custom.js');?>"></script>
    <script src="<?= $this->baseUrl('js/Chart.min.js');?>"></script>
    <script>
      /* defind global options */
      Chart.defaults.global.defaultFontFamily = base.defaultFontFamily;
      Chart.defaults.global.defaultFontColor = colors.mutedColor;
    </script>
    <script src="<?= $this->baseUrl('js/gauge.min.js');?>"></script>
    <script src="<?= $this->baseUrl('js/jquery.sparkline.min.js');?>"></script>
    <script src="<?= $this->baseUrl('js/apexcharts.min.js');?>"></script>
    <script src="<?= $this->baseUrl('js/apexcharts.custom.js');?>"></script>
    <script src='<?= $this->baseUrl('js/jquery.mask.min.js');?>'></script>
    <script src='<?= $this->baseUrl('js/select2.min.js');?>'></script>
    <script src='<?= $this->baseUrl('js/jquery.steps.min.js');?>'></script>
    <script src='<?= $this->baseUrl('js/jquery.validate.min.js');?>'></script>
    <script src='<?= $this->baseUrl('js/jquery.timepicker.js');?>'></script>
    <script src='<?= $this->baseUrl('js/dropzone.min.js');?>'></script>
    <script src='<?= $this->baseUrl('js/uppy.min.js');?>'></script>
    <script src='<?= $this->baseUrl('js/quill.min.js');?>'></script>
    <script type="text/javascript">//
        $(function(){
          $('input[type="radio"]').click(function () {
            if ($(this).is(':checked')) {
              var isi = $(this).val();
              document.getElementById('textjwb').value= isi;
              // console.log(document.getElementByClassName('number'));
                // if ($(this).val() == 'a') alert('first radio element is checked');
                // if ($(this).val() == 'b') alert('second radio element is checked');
                // if ($(this).val() == 'c') alert('third radio element is checked');
                // if ($(this).val() == 'd') alert('third radio element is checked');
                // if ($(this).val() == 'e') alert('third radio element is checked');
            }
        });
      });
        
    </script>
    <script>
      $('.select2').select2(
      {
        theme: 'bootstrap4',
      });
      $('.select2-multi').select2(
      {
        multiple: true,
        theme: 'bootstrap4',
      });
      $('.drgpicker').daterangepicker(
      {
        singleDatePicker: true,
        timePicker: false,
        showDropdowns: true,
        locale:
        {
          format: 'MM/DD/YYYY'
        }
      });
      $('.time-input').timepicker(
      {
        'scrollDefault': 'now',
        'zindex': '9999' /* fix modal open */
      });
      /** date range picker */
      if ($('.datetimes').length)
      {
        $('.datetimes').daterangepicker(
        {
          timePicker: true,
          startDate: moment().startOf('hour'),
          endDate: moment().startOf('hour').add(32, 'hour'),
          locale:
          {
            format: 'M/DD hh:mm A'
          }
        });
      }
      var start = moment().subtract(29, 'days');
      var end = moment();

      function cb(start, end)
      {
        $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
      }
      $('#reportrange').daterangepicker(
      {
        startDate: start,
        endDate: end,
        ranges:
        {
          'Today': [moment(), moment()],
          'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
          'Last 7 Days': [moment().subtract(6, 'days'), moment()],
          'Last 30 Days': [moment().subtract(29, 'days'), moment()],
          'This Month': [moment().startOf('month'), moment().endOf('month')],
          'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        }
      }, cb);
      cb(start, end);
      $('.input-placeholder').mask("00/00/0000",
      {
        placeholder: "__/__/____"
      });
      $('.input-zip').mask('00000-000',
      {
        placeholder: "____-___"
      });
      $('.input-money').mask("#.##0,00",
      {
        reverse: true
      });
      $('.input-phoneus').mask('(000) 000-0000');
      $('.input-mixed').mask('AAA 000-S0S');
      $('.input-ip').mask('0ZZ.0ZZ.0ZZ.0ZZ',
      {
        translation:
        {
          'Z':
          {
            pattern: /[0-9]/,
            optional: true
          }
        },
        placeholder: "___.___.___.___"
      });
      // editor
      var editor = document.getElementById('editor');
      if (editor)
      {
        var toolbarOptions = [
          [
          {
            'font': []
          }],
          [
          {
            'header': [1, 2, 3, 4, 5, 6, false]
          }],
          ['bold', 'italic', 'underline', 'strike'],
          ['blockquote', 'code-block'],
          [
          {
            'header': 1
          },
          {
            'header': 2
          }],
          [
          {
            'list': 'ordered'
          },
          {
            'list': 'bullet'
          }],
          [
          {
            'script': 'sub'
          },
          {
            'script': 'super'
          }],
          [
          {
            'indent': '-1'
          },
          {
            'indent': '+1'
          }], // outdent/indent
          [
          {
            'direction': 'rtl'
          }], // text direction
          [
          {
            'color': []
          },
          {
            'background': []
          }], // dropdown with defaults from theme
          [
          {
            'align': []
          }],
          ['clean'] // remove formatting button
        ];
        var quill = new Quill(editor,
        {
          modules:
          {
            toolbar: toolbarOptions
          },
          theme: 'snow'
        });
      }
      // Example starter JavaScript for disabling form submissions if there are invalid fields
      (function()
      {
        'use strict';
        window.addEventListener('load', function()
        {
          // Fetch all the forms we want to apply custom Bootstrap validation styles to
          var forms = document.getElementsByClassName('needs-validation');
          // Loop over them and prevent submission
          var validation = Array.prototype.filter.call(forms, function(form)
          {
            form.addEventListener('submit', function(event)
            {
              if (form.checkValidity() === false)
              {
                event.preventDefault();
                event.stopPropagation();
              }
              form.classList.add('was-validated');
            }, false);
          });
        }, false);
      })();
    </script>
    <script>
      $(document).ready(function(){
          $('#finish').click(function(){
              alert('Sign new href executed.');
          });
      });
    </script>
    <script src="<?= $this->baseUrl('js/apps.js');?>"></script>
  </body>
</html>